import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth"; //if use server component, check user login or not
import SessionProvider from "@/libs/SessionProvider";
import Script from "next/script";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (

    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div>
            <Navbar />
            <div className='mt-28'>
              {children}
            </div>
          </div>
        </SessionProvider>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></Script>
      </body>
    </html>
  );
}
